services:
  postgres:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=db_gacho_store
      - POSTGRES_USER=gacho
      - POSTGRES_PASSWORD=admin123
    ports:
      - 5432:5432
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
      - DATABASE_HOST=db
    ports:
      - 5050:80
    depends_on:
      - postgres